Repository NethmiK98/sample-react-app, pull requests merged in 2022-10, with the labels that each got.

#10 Navbar updated
  src/App/Navbar/Navbar.js
Labels: hacktoberfest, hactoberfest-accepted, hacktoberfest-2022

#11 Cards added
  src/App/Cards/card.js
Labels: hacktoberfest, hacktoberfect-accepted, hacktoberfest-2022

#12 Carousel one
  src/App/Carousel/carousel.js
Labels: hacktoberfest, hacktoberfect-accepted, hacktoberfest-2022

#13 Carousel two
  src/App/Carousel/carousel.js
Labels: hacktoberfest, hacktoberfect-accepted, hacktoberfest-2022

#14 Updated Navbar
  src/App/Navbar/Navbar.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-2022
